export enum MetaTagNames {
  Description = "description",
  Keywords = "keywords",
  Language = "language",
  Robots = "robots",
  OgUrl = "og:url",
  OgTitle = "og:title",
  OgDescription = "og:description",
  OgImage = "og:image",
  OgType = "og:type",
  OgLocale = "og:locale",
  OgSiteName = "og:site_name",
  TwitterCard = "twitter:card",
  TwitterTitle = "twitter:title",
  TwitterDescription = "twitter:description",
  TwitterImage = "twitter:image",
}
