import { defineNuxtPlugin } from "#app";
import PrimeVue from "primevue/config";
import TabView from "primevue/tabview";
import TabPanel from "primevue/tabpanel";
import InputText from "primevue/inputtext";
import InputNumber from "primevue/inputnumber";
import Button from "primevue/button";
import Dialog from "primevue/dialog";
import Carousel from "primevue/carousel";
import Image from "primevue/image";
import Password from "primevue/password";
import Checkbox from "primevue/checkbox";
import OverlayPanel from "primevue/overlaypanel";
import Slider from "primevue/slider";
import ProgressSpinner from "primevue/progressspinner";
import AnimateOnScroll from "primevue/animateonscroll";

export default defineNuxtPlugin((nuxtApp) => {
  nuxtApp.vueApp.use(PrimeVue);
  nuxtApp.vueApp.component("TabView", TabView);
  nuxtApp.vueApp.component("TabPanel", TabPanel);
  nuxtApp.vueApp.component("InputText", InputText);
  nuxtApp.vueApp.component("InputNumber", InputNumber);
  nuxtApp.vueApp.component("Button", Button);
  nuxtApp.vueApp.component("Dialog", Dialog);
  nuxtApp.vueApp.component("Carousel", Carousel);
  nuxtApp.vueApp.component("Image", Image);
  nuxtApp.vueApp.component("Password", Password);
  nuxtApp.vueApp.component("Checkbox", Checkbox);
  nuxtApp.vueApp.component("OverlayPanel", OverlayPanel);
  nuxtApp.vueApp.component("Slider", Slider);
  nuxtApp.vueApp.component("ProgressSpinner", ProgressSpinner);
  nuxtApp.vueApp.directive("animateonscroll", AnimateOnScroll);
});
